import Head from 'next/head'
import Link from 'next/link'
import { getFrontMatter, getSingleContent } from '@lib/mdx'
import { MDXLayoutRenderer } from '@components/MDXComponents'
import styles from '../../styles/Home.module.css'

export async function getStaticPaths() {
  const posts = await getFrontMatter('./content/articles')
  const paths = posts.map(({ slug }) => ({
    params: {
      slug: slug.split('/'),
    }
  }))

  return {
    paths,
    fallback: false,
  }
}

export async function getStaticProps({ params: { slug } }) {
  const postSlug = slug.join('/')
  const content = await getSingleContent(postSlug)

  if (!content) {
    console.warn(`No content found for slug ${postSlug}`)
  }

  return { props: { content } }
}

export default function Article({ content }) {
  const { mdxSource, frontMatter } = content

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>{frontMatter.title}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1>{frontMatter.title}</h1>
        <article>
          <MDXLayoutRenderer mdxSource={mdxSource} frontMatter={frontMatter} />
        </article>
        <footer>
          Head back{' '}
          <Link href="/">
            <a>
              <strong>
                home
              </strong>
            </a>
          </Link>
          .
        </footer>
      </div>
    </>
  )
}
