import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { getFrontMatter } from '@lib/mdx'
import styles from '../styles/Home.module.css'

export async function getStaticProps() {
  const posts = await getFrontMatter('./content/articles')
  return { props: { posts } }
}

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bidirectional links in a Next.js blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Next.js meets bidirectional links!
        </h1>

        <p className={styles.description}>
          This is a demonstration of bidirectional linking between MDX-based blog posts in a Next.js blog.
          <br />
          Click on any of the example articles below to see the bidirectional links in action.
        </p>

        <h2>Our articles:</h2>
        <div className={styles.grid}>
          {posts.map((frontMatter) => {
            const { slug, title } = frontMatter
            return (
              <Link key={slug} href={`/articles/${slug}`}>
                <a className={styles.card}>
                  <h3 className={``}>
                    {title}
                  </h3>
                </a>
              </Link>
            )
          })}
        </div>
      </main>
    </div>
  )
}
